import { Metadata } from 'next';

export const metadata: Metadata = { title: 'Privacy Policy - FileConverter Pro' };

const sections = [
  ['Information We Collect', 'We collect information you provide directly (name, email, payment details) and data generated by your use of the service (conversion history, usage analytics, and log data).'],
  ['How We Use It', 'We use your information to provide and improve the service, process payments, send transactional emails, and comply with legal obligations. We do not use your data for advertising.'],
  ['Data Sharing', 'We never sell your personal data. We share data only with trusted sub-processors (e.g., payment processors, cloud infrastructure) under strict data-processing agreements.'],
  ['Data Retention', 'Uploaded files are automatically deleted from our servers within 24 hours of conversion. Account data is retained for as long as your account is active, or as required by law.'],
  ['Security', 'All data is encrypted with AES-256 at rest and TLS 1.3 in transit. We perform regular security audits and penetration tests to protect your information.'],
  ['Cookies', 'We use essential cookies for authentication and session management, and optional analytics cookies (with your consent) to understand how the service is used. See our Cookie Policy for details.'],
  ['Your Rights (GDPR / CCPA)', 'You have the right to access, correct, export, or delete your personal data at any time. EU/EEA and California residents have additional rights under GDPR and CCPA. Contact us to exercise these rights.'],
  ['Contact', 'For privacy-related questions or to submit a data request, email privacy@fileconverterpro.com. We respond to all privacy inquiries within 30 days.'],
];

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background">
      <section className="py-20 border-b bg-gradient-to-br from-primary/5 via-transparent to-secondary/5">
        <div className="container mx-auto px-4 text-center">
          <h1 className="text-4xl md:text-5xl font-bold mb-4">Privacy Policy</h1>
          <p className="text-muted-foreground text-lg">Last updated: January 1, 2025</p>
        </div>
      </section>

      <div className="container mx-auto px-4 py-16 max-w-4xl">
        <div className="space-y-10">
          {sections.map(([title, body]) => (
            <div key={title} className="border-b pb-8 last:border-0">
              <h2 className="text-xl font-semibold mb-3 text-foreground">{title}</h2>
              <p className="text-muted-foreground leading-relaxed">{body}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
